# Generated by Django 4.2.1 on 2023-06-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genomeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome_Id', models.CharField(max_length=200)),
                ('project_Title', models.CharField(max_length=500)),
                ('run_Id', models.CharField(max_length=200)),
                ('published_Date', models.DateField()),
                ('sequencing_Platform', models.TextField()),
                ('publication_Link', models.URLField()),
            ],
        ),
    ]
